.PHONY: clean All

All:
	@echo "----------Building project:[ Solar2DConsole - Debug ]----------"
	@"$(MAKE)" -f  "Solar2DConsole.mk"
clean:
	@echo "----------Cleaning project:[ Solar2DConsole - Debug ]----------"
	@"$(MAKE)" -f  "Solar2DConsole.mk" clean
