.PHONY: clean All

All:
	@echo "----------Building project:[ Solar2DTuxConsole - Debug ]----------"
	@"$(MAKE)" -f  "Solar2DTuxConsole.mk"
clean:
	@echo "----------Cleaning project:[ Solar2DTuxConsole - Debug ]----------"
	@"$(MAKE)" -f  "Solar2DTuxConsole.mk" clean
